

export interface LiuAuthStatus {
  token: string
  serial: string
  client_key: string      // AES Key generated by frontend
}

export const liuIDETypes = [
  "vscode",
  "vscode-insiders",
  "cursor",
  "windsurf",
  "vscodium",
  "github.dev",
  "vscode.dev",
] as const

export type LiuIDEType = typeof liuIDETypes[number]

export interface LiuInfo {
  ideType: LiuIDEType
  isDesktop: boolean
  isWeb: boolean
  extensionId: string
  extensionVersion: string
  machineId: string
  sessionId: string
  uriScheme: string
  remoteName?: string
}